# Driver
CONFIG_ADC=n
CONFIG_I2C=n
CONFIG_ESPI=n
CONFIG_SPI=n
CONFIG_SPI_ASYNC=n

# console
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_LOG=y

#SHELL
CONFIG_SHELL=y
CONFIG_GPIO_SHELL=y
CONFIG_SHELL_PROMPT_UART="MCHP:~$ "

CONFIG_PM=y
