# Driver
CONFIG_EEPROM=y

# console
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_LOG=y

#SHELL
CONFIG_SHELL=y
CONFIG_GPIO_SHELL=y
CONFIG_EEPROM_SHELL=y
CONFIG_SHELL_PROMPT_UART="MCHP:~$ "

# RETENTION
CONFIG_RETAINED_MEM=y
CONFIG_RETENTION=y

CONFIG_REBOOT=y
