# Driver
CONFIG_SPI=y
# CONFIG_SPI_INIT_PRIORITY=49
CONFIG_FLASH=y
# CONFIG_FLASH_EX_OP_ENABLED=y
# CONFIG_FLASH_INIT_PRIORITY=51

# console
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_LOG=y

#SHELL
CONFIG_SHELL=y
CONFIG_GPIO_SHELL=y
CONFIG_FLASH_SHELL=y
CONFIG_SHELL_PROMPT_UART="MCHP:~$ "

# RETENTION
CONFIG_RETAINED_MEM=y
CONFIG_RETENTION=y

CONFIG_REBOOT=y
